# Generated by Django 4.2.1 on 2023-05-23 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('C', 'Completed')], default='O', max_length=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_games', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameHandAndBrain',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.game')),
                ('current_piece', models.CharField(blank=True, max_length=10, null=True)),
                ('team1_brain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_games_brain', to=settings.AUTH_USER_MODEL)),
                ('team1_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_games_head', to=settings.AUTH_USER_MODEL)),
                ('team2_brain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_games_brain', to=settings.AUTH_USER_MODEL)),
                ('team2_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_games_head', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('game.game',),
        ),
    ]
